services:
  db:
    image: postgres:16
    container_name: swimdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: swim
      POSTGRES_PASSWORD: swim
      POSTGRES_DB: swimsmart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swim -d swimsmart"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swimsmart-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.docker
    ports:
      - "8000:8000"
    restart: unless-stopped
    # optional live-reload during local dev (uncomment next 2 lines if you want hot reload)
    # volumes:
    #   - .:/app

volumes:
  pgdata:
